export const TEST_TOGGLE = 'TEST_TOGGLE';

export const REQUEST_TEST_TEXT = 'REQUEST_TEST_TEXT';
export const REQUEST_TEST_TEXT_FAILED = 'REQUEST_TEST_TEXT_FAILED';
export const RECEIVE_TEST_TEXT = 'RECEIVE_TEST_TEXT';
